name: CI

on:
    pull_request:
    push:
        branches:
            - "**"

jobs:
    linux-ci:
        name: Linux Build and Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Zig
              uses: mlugg/setup-zig@v2.2.1
              with:
                  version: master

            - name: Show Zig version
              run: zig version

            - name: Type-check
              run: zig build check

            - name: Build
              run: zig build

            - name: Run tests
              run: zig build test

